name: RSpec Tests

on:
  pull_request: # Trigger on any pull request
  push:
    branches:
      - main # Trigger only when branches are merged into main

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2 # Adjust to your Ruby version
          bundler-cache: true

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create db:schema:load

      - name: Run RSpec tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec
          COVERAGE=$(bundle exec simplecov-console | grep -oP '\d+(?=% coverage)')
          if [ "$COVERAGE" -lt 90 ]; then
            echo "Coverage is below 90% ($COVERAGE%)"
            exit 1
