name: RSpec Tests

on:
  pull_request: # Trigger on any pull request
  push:
    branches:
      - master # Trigger only when branches are merged into master

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
          bundler: '2.4.22'
          bundler-cache: true
          cache-version: 0

      - name: Install simplecov-console
        run: |
          gem install simplecov-console

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create db:schema:load

      - name: Run RSpec tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rspec
