name: Rubocop Linting

on:
  pull_request: # Trigger on any pull request
  push:
    branches:
      - main # Trigger only when branches are merged into main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2 # Adjust to your Ruby version
          bundler-cache: true

      - name: Run RuboCop
        run: |
          bundle exec rubocop